### ISSUE TITLE
Missing file 'co-occur.pk'

### ISSUE THREAD

**Issue by proevgenii** [yuewan2/Retroformer#1]
Hello! 
Great job, great repository thanks for it! 
But when I run train.py, I get an error with missing file : **'co-occur.pk'.** It is read in a file **dataset.py** in line 59 (add pic.) and assigned to a variable **self.co_occur_matrix**, but this variable never used.
 Can you help me solve this problem, thanks!
![image](https://user-images.githubusercontent.com/70540457/155856900-c09174c1-9f23-466c-a038-fe6502768a0a.png)

**Comment by yuewan2** [comment]
Hi. Thank you for your interest! I have already fixed the issue. Thank you for pointing this out.
