### ISSUE TITLE
how to reproduce the results in the paper?

### ISSUE THREAD

**Issue by LaHauzel** [yuewan2/Retroformer#2]
following the instruction, i downloaded the dataset and checkpoints, and successfully finished the "translate.sh" script.

however, with the checkpoint without reaction type, the accuracy is quite different from the one in the paper: 
```text
Top-1: 0.5289
Top-2: 0.6363
Top-3: 0.682
Top-4: 0.7076
Top-5: 0.725
Top-6: 0.7346
Top-7: 0.7452
Top-8: 0.7525
Top-9: 0.7601
Top-10: 0.7639
```

can you help me?  any help would be much appreciated

**Comment by yuewan2** [comment]
Thanks for your interest! This result is from the "naive" inference setting. You can set --stepwise to True to enable the "subgraph search" inference setting, where reaction center search and ranking are performed. Then it corresponds to the best results in the paper.

**Comment by LaHauzel** [comment]
> Thanks for your interest! This result is from the "naive" inference setting. You can set --stepwise to True to enable the "subgraph search" inference setting, where reaction center search and ranking are performed. Then it corresponds to the best results in the paper.

nice work!  i followed your instruction and succeeded!

```text

Top-1: 0.5317
Top-2: 0.6547
Top-3: 0.711
Top-4: 0.745
Top-5: 0.7653
Top-6: 0.7817
Top-7: 0.7969
Top-8: 0.8075
Top-9: 0.8149
Top-10: 0.8201

```

**Comment by yuzhou2333** [comment]
Dear author and LaHazel, I meet a question, when i run the translate.sh and set the stepwise=True,i can only get the 0.7352,how can i get the result as the same as the article?
![image](https://github.com/yuewan2/Retroformer/assets/74141246/ac6a809e-1f66-4caf-a62f-ce486375667f)
![image](https://github.com/yuewan2/Retroformer/assets/74141246/8191ab67-fe75-459f-b2fa-73eef7e345d6)
![image](https://github.com/yuewan2/Retroformer/assets/74141246/27874452-72f4-4e4d-a3db-22f6c83742c9)
![image](https://github.com/yuewan2/Retroformer/assets/74141246/6e6eae33-d935-43e0-ad7c-f74c3fc5f685)
![image](https://github.com/yuewan2/Retroformer/assets/74141246/e9be78da-d49c-459a-b7aa-b6bf4e7d5274)
