### ISSUE TITLE
How to get top-100 accuracy?

### ISSUE THREAD

**Issue by LaHauzel** [yuewan2/Retroformer#3]
sorry for bothering you again.

i would like to get the top-100 accuracy of the uspto-50k dataset, and changed the `beam_size` parameter in the translation script.  
keeping the `stepwise == True`, i got the following results:
```text
Top-1: 0.5317
Top-2: 0.6547
Top-3: 0.711
Top-4: 0.745
Top-5: 0.7653
Top-6: 0.7817
Top-7: 0.7969
Top-8: 0.8075
Top-9: 0.8149
Top-10: 0.8201
Top-11: 0.8201
Top-12: 0.8201
Top-13: 0.8201
Top-14: 0.8201
Top-15: 0.8201
Top-16: 0.8201
Top-17: 0.8201
Top-18: 0.8201
Top-19: 0.8201
Top-20: 0.8201
Top-21: 0.8201
Top-22: 0.8201
Top-23: 0.8201
Top-24: 0.8201
Top-25: 0.8201
Top-26: 0.8201
Top-27: 0.8201
Top-28: 0.8201
Top-29: 0.8201
Top-30: 0.8201
Top-31: 0.8201
Top-32: 0.8201
Top-33: 0.8201
Top-34: 0.8201
Top-35: 0.8201
Top-36: 0.8201
Top-37: 0.8201
Top-38: 0.8201
Top-39: 0.8201
Top-40: 0.8201
Top-41: 0.8201
Top-42: 0.8201
Top-43: 0.8201
Top-44: 0.8201
Top-45: 0.8201
Top-46: 0.8201
Top-47: 0.8201
Top-48: 0.8201
Top-49: 0.8201
Top-50: 0.8201
....
```
it seems that the top-k accuracy with k > 10 is the same as the top-10 one.

all of my modification is adding the `beam_size` parameter to the function, from
```python
pred_tokens, pred_scores, predicts = \
                translate_batch_stepwise(model, batch, invalid_token_indices=invalid_token_indices,
                                         T=10, alpha_atom=-1, alpha_bond=-1,
                                         beta=0.5, percent_aa=40, percent_ab=percent_ab, k=3,
                                         use_template=args.use_template == 'True',
                                         factor_func=dataset.factor_func,
                                         reconstruct_func=dataset.reconstruct_smi,
                                         rc_path=args.intermediate_dir + '/rt2reaction_center.pk')
```
to 
```python
pred_tokens, pred_scores, predicts = \
                translate_batch_stepwise(model, batch, beam_size=args.beam_size, invalid_token_indices=invalid_token_indices,
                                         T=10, alpha_atom=-1, alpha_bond=-1,
                                         beta=0.5, percent_aa=40, percent_ab=percent_ab, k=3,
                                         use_template=args.use_template == 'True',
                                         factor_func=dataset.factor_func,
                                         reconstruct_func=dataset.reconstruct_smi,
                                         rc_path=args.intermediate_dir + '/rt2reaction_center.pk')
```

is there any wrong?

**Comment by yuewan2** [comment]
Hi LaHauzel, thank for for pointing this out. It turns out there is a _hard-coded beam_size=10_ at line 122 in 'translate.py' file. I have already fixed this issue! Please try it out with the latest version. However I do not recommend setting beam_size to be this large since it is highly likely for molecule sequence generation model to generate invalid results at large k.

**Comment by LaHauzel** [comment]
> Hi LaHauzel, thank for for pointing this out. It turns out there is a _hard-coded beam_size=10_ at line 122 in 'translate.py' file. I have already fixed this issue! Please try it out with the latest version. However I do not recommend setting beam_size to be this large since it is highly likely for molecule sequence generation model to generate invalid results at large k.

great work! thanks for your quick reply! i succeeded to make predictions with a large beam size and thanks for you advice!  have a nice day!
