### ISSUE TITLE
Model parameters

### ISSUE THREAD

**Issue by SII-ShenggengLin** [yuewan2/Retroformer#4]
Hello, I downloaded the data set and code. And retrained the model. When the reaction class was not known, the results obtained were different from those reported in the paper. Are the parameter Settings in the code the ones in the paper? Thank you very much! Here's what I got.
Top-1: 0.4128
Top-2: 0.5233
Top-3: 0.5756
Top-4: 0.603
Top-5: 0.6239
Top-6: 0.6409
Top-7: 0.6537
Top-8: 0.6649
Top-9: 0.6745
Top-10: 0.6812

**Comment by yuewan2** [comment]
The default max_step=10k is only enough for training the non-augmented version. The best results (with augmentation) in the paper is trained by max_step=50k and with the batch_size_token=16384.

**Comment by SII-ShenggengLin** [comment]
ok, thanks very much! I will try it again!

**Comment by zixun-lan** [comment]
Hi, [ShenggengLin](https://github.com/ShenggengLin). Has the accuracy of top1 reached 53% after you retrained the model according to the author's configuration?
