### ISSUE TITLE
lmdb.open(os.path.join(self.data_folder, 'cooked_{}.lmdb'.format(self.mode)), lmdb.Error: ./data/uspto50k\cooked_train.lmdb: ���̿ռ䲻�㡣

### ISSUE THREAD

**Issue by zhujiajun2023** [yuewan2/Retroformer#6]
File "C:\Users\Zhujiajun\anaconda3\envs\zhu\lib\site-packages\retroformer\dataset.py", line 135, in build_processed_data
    env = lmdb.open(os.path.join(self.data_folder, 'cooked_{}.lmdb'.format(self.mode)),
lmdb.Error: ./data/uspto50k\cooked_train.lmdb: ���̿ռ䲻�㡣

网上查阅这边报错是 map-size设置过大导致？请问这边map-size设置多大合适？

**Comment by yuewan2** [comment]
你好！我的map-size hardcode成了1T, 不过你可以设置成1G的试试。
